### ISSUE TITLE
[ethers] uint8 returned data is infered as BigNumber, but ethers return number instead

### ISSUE THREAD

**Issue by andrevmatos** [ethereum-ts/TypeChain#142]
For constant methods (at least), uint8 numbers (at least) are returned as numbers by ethers.js Contract, but TypeChain generate bindings as if they were `BigNumber`.

**Comment by krzkaczor** [comment]
Thanks! Yes, I think someone reported this to me as well. Maybe you want to prepare a PR fixing it? 

@ricmoo can we simply assume that for every [u]intX where x < 8 ethers returns number instead of BigNumber? What are the rules?

**Comment by ricmoo** [comment]
The rule is if x <= 53 (but since x must be congruent to 0 mod 8, that means x <= 48 or less) it is an ieee 754 Number, otherwise it is a BigNumber. This is the reason the coerceFunction can be overridden, and in v5, a contract subclass can override the the _abiCoder method to change this behaviour.

V5 is almost ready for public beta, but there isn’t any documentation yet.

You can see this implemented in the defaultCoerceFunc in the src.ts/utils/abi-coder in v4 (or the `@ethersproject/abi` in the v5 branch). If you wish to override this behaviour that will also show you how to. :)

Types which are uint48 or int48 or smaller in width, are safe in JavaScript, as they fit within the floating-point mantissa.

**Comment by andrevmatos** [comment]
#144 implements this, tested here with Token `decimals` and it works.
