### ISSUE TITLE
Support Function Overloading

### ISSUE THREAD

**Issue by PhABC** [ethereum-ts/TypeChain#150]
As of now, it seems like generated types do not support function overload. Would it be possible to add support for this?

This feature has been mentioned in #106 but I haven't seen any update since that issue was opened.

**Comment by krzkaczor** [comment]
It's supported on ABI parser level. Now support for all targets is missing.

**Comment by pash7ka** [comment]
@krzkaczor I can work on this, if you give me some clue how to approach this problem. As i understand, there is no support in TypeScript for overloading functions with different signatures, it only allows to ommit some parameters.
My current work-around is to convert to `<any>` and then use `methods` field of a contract oblect:
```
let instance = await MyInitializableContract.new();
await (<any> instance ).methods['initialize(address)'](myInitData, {from: owner});
```
One approach would be to have functions with names like `method_0xc4d66de8` where `0xc4d66de8` is first 4 bytes of `keccak256('initialize(address)')`.

**Comment by krzkaczor** [comment]
@pash7ka I am glad that you're up for the task ;) So let me start by emphasizing that we don't come up with our own API but rather conform to API that is used by target library. 

As far as I remember most of libs choose somehow default (first in abi?)  implementation (so for example named simply `initialize`) and then use full names (with args) for overloads (for example: `initialize(address)`). So here we don't actually need any overloading on the level of generated wrappers - there are simply functions with different names.

TypeChain will group entities (methods/events) by name so it's quite easy to generate code for all overloads, for now we just pick first impl.

Let me know if you have any questions, for starters just focus on one target. Probably in few weeks (or even sooner) I will work on this by myself because it's a high time 😆

**Comment by pash7ka** [comment]
>As far as I remember most of libs choose somehow default (first in abi?) implementation 

For example, Web3.js implementaions has special handling for such case. They [create a linked list of implementations](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-contract/src/index.js#L134) and [iterate through it](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-contract/src/index.js#L774) until number of arguments does not match.

> then use full names (with args) for overloads (for example: `initialize(address)`). 

I believe TypeScript does not allow parenthesis in function names. 

Let's get to example. Currently, for truffle, i may have:
```
export interface IMyInitializableContractInstance extends Truffle.ContractInstance {
  initialize: {
    (myArg1: string | BN, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(/*...*/): Promise<void>;
    sendTransaction(/*...*/): Promise<string>;
    estimateGas(/*...*/): Promise<number>;
  };
}
```
or, if I'm not lucky enough to have expected implementaion:
```
export interface IMyInitializableContractInstance extends Truffle.ContractInstance {
  initialize: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(/*...*/): Promise<void>;
    sendTransaction(/*...*/): Promise<string>;
    estimateGas(/*...*/): Promise<number>;
  };
}
```
So what we should generate to fix this issue?

If there is no quick-and-easy answer for this, maybe it's better to wait a few weeks until you can get to it. No rush.

**Comment by krzkaczor** [comment]
@pash7ka thanks for this insight! If I am not gonna pick this up in January feel free to work on this (but there are high chances that I will 😆 )

**Comment by pash7ka** [comment]
@krzkaczor The problem is, that i do not understand which is the good way to do it. So i guess it will wait for you. Hope it will be soon.
