### ISSUE TITLE
How to load contract with web3@1.x

### ISSUE THREAD

**Issue by kiliw** [ethereum-ts/TypeChain#151]
I did not find any example on how to load a contract which is already deployed on the chain with the bindings / definitions for target web3@1.x. I assume one must somehow create a contract with `new web3.eth.Contract` and cast it to the type generated by typechain.

But `web.eth.Contract` needs the `abi`. I dirtily load the `abi` from the `.json` file but I cannot call the methods because "out of gas". Could someone provide a working example? Thanks!

**Comment by krzkaczor** [comment]
>  I assume one must somehow create a contract with new web3.eth.Contract and cast it to the type generated by typechain.

Yes, this is exactly what you need to do. Typechain provides only typings so if you're getting out of gas errors there's somewhere problem on your end. 

Idea: first try to make it work without typechain (with anys) and once it works cast it to typechain type and develop further. FYI: Out of gas errors could be rejected txs in disquise.

I am gonna close it since it's not releated to TypeChain itself.

**Comment by kiliw** [comment]
@krzkaczor Thank you very much for your answer, I will have a look into it.
