### ISSUE TITLE
Why legacy target was remove?

### ISSUE THREAD

**Issue by elranu** [ethereum-ts/TypeChain#183]
Hi,
        why legacy target was remove from the readme? Legacy target works great with metamask that has web3 0.20.X

Regards,
Mariano

**Comment by krzkaczor** [comment]
Yes... so I decided to not migrate legacy target to v1.0.0 (even though it's possible). I thought no one uses it since web3 1.x.x got pretty good. 

I think there was no ongoing development for legacy target anyway, maybe I will just leave a pointer in readme that people should use older version if they want to use legacy target.

**Comment by krzkaczor** [comment]
Please reopen if more people need this.
