### ISSUE TITLE
Allow shell glob

### ISSUE THREAD

**Issue by AuHau** [ethereum-ts/TypeChain#214]
Hey there,

first of all thanks for a great tool! This really makes much more comfortable to develop with contracts in TS!

One small issue I had is that your CLI args parsing does not allow using shell globbing patterns (eq. shell expansion) because you expect only one glob argument and therefore when shell expands the glob into list of paths the CLI detects only one file instead of all of them. 

Wrapping the glob parameter in parenthesis fix this, but takes time to realize what is going on 😅

**Comment by krzkaczor** [comment]
Yeah, it's PITA, it's even mentioned in readme docs but you're right - this could be supported on CLI level. Thanks for this suggestion 👍

**Comment by AuHau** [comment]
Oh damn, sorry about that 🙈I have missed that in docs. I will have a look if it could be easily worked on and create PR if so.

**Comment by krzkaczor** [comment]
@AuHau you're more than welcome to do so :) 

I think this can be a little bit more complicated because glob handling could be a part of https://github.com/krzkaczor/ts-generator 

anyway, one more reason to merge TypeChain with ts-generator (since it failed to succeed as a separate project) and simplify things.

**Comment by AuHau** [comment]
I see, well I am already too much procrastinating today, so not sure when exactly I will get to it 😅
