### ISSUE TITLE
Name collisions with `${contract.name}Factory.ts`

### ISSUE THREAD

**Issue by dapplion** [ethereum-ts/TypeChain#225]
When using the ethers target with projects that have Factory contracts
- [ENSFactory.sol](https://github.com/aragon/aragonOS/blob/v4.4.0/contracts/factory/ENSFactory.sol)
- [ENS.sol](https://github.com/aragon/aragonOS/blob/c85d34e4bae0bf5b1ab78340b32e712d895179a7/contracts/lib/ens/ENS.sol)

The generated factory of ENS collides with the actual ENSFactory and overwrites its instance.

To solve this, maybe the name pattern could be customized? Or store instance files and factory files in different folders

**Comment by 0xGabi** [comment]
Bump. Is there a fix to prevent the overwrites?

**Comment by krzkaczor** [comment]
Not really but this should be really fixed.

I am thinking that perhaps we should create factories as part of the type file instead of a separate file. WDYT: @quezak?

**Comment by quezak** [comment]
I think generating factories to a subdirectory would be better. The factory files are big since they include the full ABI JSON, so if someone doesn't need them he can just skip these files then.

An even simpler solution would be to name the file in a way that's not colliding - the contract filenames have their punctuation removed, so we could safely name the factory files like `ContractName.factory.ts` or `ContractName__factory.ts`.

**Comment by krzkaczor** [comment]
Yeah, this makes sense. I think a separate dir is the best option. I am not 100% sure if we normalize filenames (this is for sure the case for type **names**).

Open for PRs. This will be a breaking change for target. This should be fixed in both ethers v4 and v5 targets.

**Comment by 0xGabi** [comment]
Hey I opened a PR with an attempt to fix the issue. Let me know what you think 🙌

**Comment by krzkaczor** [comment]
Released as:
```
@typechain/ethers-v5@3.0.0
@typechain/ethers-v4@3.0.0
```
