### ISSUE TITLE
Is the intended use of the Factory non-type .ts file documented?

### ISSUE THREAD

**Issue by pcowgill** [ethereum-ts/TypeChain#251]
I'm curious what the purpose of the `...Factory.ts` file is in a project like this:

```
types/Greeter.d.ts
types/GreeterFactory.ts
types/index.d.ts
```

Is that documented somewhere? I'm not sure if this question is ethers-specific or not. Thanks!

**Comment by krzkaczor** [comment]
CC: @quezak, I guess we should write some docs about it...

**Comment by quezak** [comment]
Yes. I'll write a short overview here, @pcowgill please tell us what should be described more.

The factory classes are an extension of ethers' `ContractFactory`. They serve two main purposes:
* wrap passing contract ABI and bytecode to the `ContractFactory` class, so you don't have to load and parse the JSON manually
* provide a correctly typed interface to `ContractFactory` (since it returns plain `Contract` instances).

Another case are abstract contracts or solidity interfaces, because they have no bytecode. For those, a simplified factory is generated that doesn't extends `ContractFactory`, and only includes the static `connect` method, so you can easily connect to a deployed instance without having to pass the ABI manually.

Very simple example: 
```typescript
// suppose you have an `Erc20Token` solidity interface and a `DummyToken` contract implementing it

import { BigNumber } from 'ethers/utils';
import { Wallet } from 'ethers';

import { DummyTokenFactory } from '@contracts/DummyTokenFactory';
import { DummyToken } from '@contracts/DummyToken';
import { Erc20TokenFactory } from '@contracts/Erc20TokenFactory';

const provider = getYourProvider(...);

// use the concrete contract factory if you need to operate on the bytecode (ie. deploy)
async function deployTestToken(ownerPK: string): Promise<DummyToken> {
    const owner = new Wallet(ownerPK, provider);
    return new DummyTokenFactory(owner).deploy();
}

// to call existing contracts, a factory for both the concrete contract and for the interface
// can be used since the ABI is the same
async function getTokenBalance(walletAddress: string, tokenAddress: string): Promise<BigNumber> {
    const token = Erc20TokenFactory.connect(tokenAddress, provider);
    return token.functions.balanceOf(address);
}
```

**Comment by pcowgill** [comment]
@quezak Thanks very much for this info!! I think that's basically the info I would expect to see in the ethers-v4 target package's README [here](https://github.com/ethereum-ts/TypeChain/blob/master/packages/target-ethers-v4/README.md). So most of that can be pasted in in a PR directly, if that sounds good to you.

Also, thoughts on putting the factory .ts files in a different subdir than the .d.ts type files by default for that target package? If I understand correctly, it seems that the purpose each serves is quite different.

**Comment by pcowgill** [comment]
In your example above, the DummyTokenFactory would most likley be in a `types` or `typechain` dir, while the contract itself would be in a separate `contracts` dir. So to make that clearer what comes from TypeChain and what doesn't in the example, it might be worth changing those import lines. Other than that, the example is perfect!

**Comment by quezak** [comment]
Thanks for the feedback! The `@contracts` path is actually an alias to `build/contracts` where typechain generates files in one of my own projects, but I see how the name can be misleading :) So, all the files imported from that dir are generated by typechain in the example.

Re `.ts` vs `.d.ts` -- this is actually another problem. We could start generating the factories into another dir, but personally I'd like to refactor the target to generate regular `.ts` files with actual classes extending ethers `Contract`. Currently only declarations are generated, so you can't use the typed contract info at runtime. This causes many problems, for example you can't use `contractInstance.constructor.name`, can't use `instanceof MyContract`, pass the contract class as a parameter, and write generic functions that operate on instances of different contracts (and if you try, it fails with misleading error messages, because it's not easy to notice that the generated classes are just not available at runtime).

**Comment by quezak** [comment]
I've added a simple [readme](https://github.com/ethereum-ts/TypeChain/blob/master/packages/target-ethers-v4/README.md) including what I've wrote above plus some basic info about contract type declarations. Thanks @pcowgill for the suggestion!
