### ISSUE TITLE
TypeChain says return type is string when its uint256

### ISSUE THREAD

**Issue by TransmissionsDev** [ethereum-ts/TypeChain#275]
Type definitions:

![ScreenShot-](https://user-images.githubusercontent.com/26209401/90319972-cca3e880-def1-11ea-8229-fed79cf72e49.png)

ABI type:

![ScreenShot-](https://user-images.githubusercontent.com/26209401/90319974-d2013300-def1-11ea-9bc4-9bdc8a42b038.png)

I'm using `web3-v1` as the target.

**Comment by krzkaczor** [comment]
Which target did you use? I am pretty sure it's expected, just inspect values in runtime. 

Simply, your ethereum access library (ethers/web3/truffle) chooses to return `uints` as strings because of `number` type limitations in JS. You should probably use BigNumber like library do perform math on such values.

**Comment by TransmissionsDev** [comment]
Ah that makes sense. And as I said in the original issue, I'm using `web3-v1`.
