### ISSUE TITLE
Typechain fails when there is a `provider` method on contract 

### ISSUE THREAD

**Issue by gbarros** [ethereum-ts/TypeChain#298]
![image](https://user-images.githubusercontent.com/1740378/98383527-5bc12800-202b-11eb-860c-c5497bc65072.png)
with the error message: 
```
Property 'provider' in type 'MMInstantiator' is not assignable to the same property in base type 'Contract'.
  Type '(_index: BigNumberish, overrides?: CallOverrides | undefined) => Promise<string>' is not assignable to type 'Provider'.ts(2416)
Class 'Contract' defines instance member property 'provider', but extended class 'MMInstantiator' defines it as instance member function.ts(2425)
```

If I rename it, then all issues go away. Currently, I cannot lightly rename this method since there are deployed contracts already working with the current ABI.

**Comment by krzkaczor** [comment]
Good call. Which target do you use?

These methods should be always accessible as `contract.methods` (or .functions I don't remember), sooo a quick fix for it would be to filter out conflicting names while generating top-level aliases.

**Comment by quezak** [comment]
hmm, I wonder what does Ethers itself do in this case? Because our generated class is just a type layer on top of it, so when instantiated it will still have to somehow deal with trying to create a `provider` function on the contract object where there already is a `provider: Provider` property.

Question: if you instantiate a plain ethers `Contract` with the ABI of your contract, is `provider` the property containing the JsonRPC provider, or is it a function that calls your method?

**Comment by krzkaczor** [comment]
Yeah, I assumed that it will not override this method. Anyway it can be hard to generate types for this property so I would just print out the warning and not touch it at all. It can be always accessed via `.methods`.

**Comment by zemse** [comment]
>  I wonder what does Ethers itself do in this case?

ethers have two ways of calling a method, using the function and signature string:

```ts
contract.balanceOf('0xaddr')
contract['balanceOf[uint256]']('0xaddr')
```

AFAIK, when there are some conflicts with ethers reserved properties on the `contract` like `provider` in this case, ethers.js drops that function but the alternate method is available. There was an issue on ethers repo maybe a year back, I couldn't find it to link here.

```ts
contract['provider(uint256)'](123)
```

@gbarros You can use this alternate syntax in your project. And until this problem is fixed, whenever you run typechain you'd just need to remove the function. And the fix is probably about removing functions with reserved names.

**Comment by quezak** [comment]
Thanks @zemse for clarifying how ethers handle this.

So yes, the fix is to stop generating `contract.functionName` typing for methods whose name collides with ethers `Contract` class properties. PRs are welcome :smiley:

**Comment by gbarros** [comment]
I took a look at what ether does and it's exactly like you thought, it ignores the method from the contract and it keeps `provider: JsonRpcProvider {...}`. Thanks for the help guys!

**Comment by krzkaczor** [comment]
Released: https://github.com/ethereum-ts/TypeChain/releases/tag/typechain%404.0.1
